name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
        
      - name: run unit test
      - run: ci/unit-test-app.sh
